### ISSUE TITLE
Symfony deprecations

### ISSUE THREAD

**Issue by dannyvw** [Sylius/SyliusMailerBundle#101]
Since symfony/config 5.1: The signature of method "Symfony\Component\Config\Definition\Builder\NodeDefinition::setDeprecated()" requires 3 arguments: "string $package, string $version, string $message", not defining them is deprecated.

`->setDeprecated('The "subject" option is deprecated since SyliusMailerBundle 1.5')`

-----

Since symfony/dependency-injection 5.2: The "Symfony\Component\DependencyInjection\Definition::setPrivate()" method is deprecated, use "setPublic()" instead.

`$swiftmailerAdapter->setPrivate(false);`

**Comment by NoResponseMate** [comment]
Hi @dannyvw 👋 

Both of these issues were fixed in #145 as a part of 2.0.

Cheers :beers:
